### ISSUE TITLE
decide where to install library

### ISSUE THREAD

**Issue by dmalan** [cs50/libcs50-java#6]
`Makefile` needs to be updated to have packages install `cs50.jar` and `docs` in some standard directories.

**Comment by kzidane** [comment]
@dmalan I think it's more typical to explicitly specify a classpath, but I know the goal may be to simplify things for students so that they don't have to to worry about classpaths, etc specially at the beginning. 

per this document https://docs.oracle.com/javase/tutorial/ext/basics/install.html, the jar should go into `/usr/java/packages/lib/ext`, if we want it to be used by possibly several JREs on the system.

regarding docs, not sure if there's a standard directory for them (they typically exist online). e.g., IDEs often provide ways<sup>1</sup> to manually attach source directories (or archives) and/or javadoc URLs (or archives) with a jar file to allow developers to see source code (e.g., while debugging) and docs (e.g., when hovering a method name, etc).

---

<sup>[1]</sup> Eclipse examples: http://stackoverflow.com/a/13857564/1797347 and http://stackoverflow.com/a/11579339/1797347!

**Comment by dmalan** [comment]
Sounds good. Want to tweak the `Makefile` accordingly?

**Comment by kzidane** [comment]
Will do.

**Comment by kzidane** [comment]
Done per #9!

**Comment by dmalan** [comment]
Thanks!
